Support runtime gltf operations.
godot-extended-libraries/godot-fire pull request #3
Opened 2021-04-06 04:28 UTC by fire

For review.

2021-04-06 04:49 UTC, lyuma requested changes
Mostly good. We should make sure to add explicit security checks and migrate any URI resolving code for textures & buffers & etc. into a common helper which has explicit "" check that returns ERR_FAIL_...

2021-04-06 04:49 UTC, lyuma commented on modules/gltf/editor_scene_importer_gltf.cpp
> +	ClassDB::bind_method(D_METHOD("import_gltf_scene_buffer", "buffers", "flags", "bake_fps", "state"),
"buffer", not "buffers"

2021-04-06 04:49 UTC, lyuma commented on modules/gltf/editor_scene_importer_gltf.cpp
> +	return cast_to<Node3D>(root);
This block of code should be moved into a function to be shared with the non _buffer version

2021-04-06 04:49 UTC, lyuma commented on modules/gltf/gltf_document.cpp
> +	err = _parse_buffers(state, "");
_parse_buffers must be modified to guarantee that no URI resolves are done if p_base_path is ""

2021-04-06 04:49 UTC, lyuma commented on modules/gltf/gltf_document.cpp
> +	err = _parse_images(state, "");
_parse_buffers must be modified to guarantee that no URI resolves are done if p_base_path is ""

2021-04-06 04:49 UTC, lyuma commented on modules/gltf/gltf_document.cpp
> +	state->major_version = version.get_slice(".", 0).to_int();
Everything from this point on must be merged into a common function with `parse()` and pass "" as the p_base_path, which we will handle specially later on.

2021-04-06 06:20 UTC, fire commented
PackedScene should have a convert function from EditorSceneImporterMeshNode to MeshInstance

2021-09-08 17:25 UTC, fire commented
> @fire it looks good. We got quite a lot of demand to make the GLTF importer part of core, given it is needed for VR and other stuff, so I have the feeling we should optimize it for performance (which we should do anyway) and have an option to load actual meshes instead of EditorImporterMesh.. so that means we would need to provide a function to parse the mesh node into a scene node and the editor supplies, otherwise it uses Mesh as a default

From reduz

2021-09-08 17:44 UTC, closed without merging